"""Create (or reset) a dedicated end-to-end test user.

Why a separate script:
  - Running E2E against a real person's account (like Irina's) risks
    burning failed-login attempts toward the lockout threshold.
  - A dedicated e2e-test@victoriaenso.com account can be reset, locked,
    and generally abused without consequence.

Usage:
  # Create or reset, writing creds to apps/staff-portal/.env.e2e
  python tools/scripts/seed_e2e_test_user.py --apply

  # Reset password only (user must already exist)
  python tools/scripts/seed_e2e_test_user.py --apply --reset-only

The generated .env.e2e is gitignored (see .gitignore) and is read by
`npm run test:e2e` via `--env-file` / direct `process.env` in CI.
"""
from __future__ import annotations

import argparse
import os
import secrets
import string
import sys
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

# Path shims so this works whether invoked from repo root or elsewhere.
REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND = REPO_ROOT / "backend"
sys.path.insert(0, str(BACKEND))

import firebase_admin  # noqa: E402
from firebase_admin import auth, credentials, firestore  # noqa: E402

TEST_EMAIL = "e2e-test@victoriaenso.com"
TEST_DISPLAY_NAME = "E2E Test User"
ENV_FILE = REPO_ROOT / "apps" / "staff-portal" / ".env.e2e"

_PW_ALPHABET = string.ascii_letters + string.digits


def generate_password(length: int = 20) -> str:
    return "".join(secrets.choice(_PW_ALPHABET) for _ in range(length))


def init_firebase() -> firestore.Client:
    """Initialise the Admin SDK the same way the backend does."""
    if not firebase_admin._apps:
        # Prefer ADC if available; otherwise look for the service-account key
        # at the same path the backend uses.
        sa_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
        if sa_path and Path(sa_path).exists():
            firebase_admin.initialize_app(credentials.Certificate(sa_path))
        else:
            firebase_admin.initialize_app()
    return firestore.client()


def ensure_auth_user(*, reset_password: bool) -> tuple[str, str | None]:
    """Return (firebase_uid, new_password_if_set)."""
    try:
        record = auth.get_user_by_email(TEST_EMAIL)
        if reset_password:
            pw = generate_password()
            auth.update_user(
                record.uid,
                password=pw,
                email_verified=True,
                display_name=TEST_DISPLAY_NAME,
                disabled=False,   # in case it got locked out during a prior run
            )
            # Revoke any lingering refresh tokens from previous runs so old
            # browser sessions can't silently keep working.
            auth.revoke_refresh_tokens(record.uid)
            return record.uid, pw
        return record.uid, None
    except auth.UserNotFoundError:
        pw = generate_password()
        record = auth.create_user(
            email=TEST_EMAIL,
            password=pw,
            display_name=TEST_DISPLAY_NAME,
            email_verified=True,
        )
        return record.uid, pw


def ensure_firestore_user(db: firestore.Client, firebase_uid: str) -> str:
    """Upsert users/{id} keyed by firebase_uid. Return user_id."""
    existing = list(
        db.collection("users").where("firebase_uid", "==", firebase_uid).limit(1).stream()
    )
    now = datetime.now(timezone.utc)
    if existing:
        user_id = existing[0].id
        db.collection("users").document(user_id).set({
            "firebase_uid": firebase_uid,
            "email": TEST_EMAIL,
            "full_name": TEST_DISPLAY_NAME,
            "updated_at": now,
        }, merge=True)
        return user_id
    user_id = str(uuid4())
    db.collection("users").document(user_id).set({
        "id": user_id,
        "firebase_uid": firebase_uid,
        "email": TEST_EMAIL,
        "full_name": TEST_DISPLAY_NAME,
        "phone": None,
        "created_at": now,
        "updated_at": now,
    })
    return user_id


def write_env_file(email: str, password: str) -> None:
    """Write creds at 0600 so they don't leak to other users on the box."""
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(
        f"# E2E test user credentials. Auto-generated by seed_e2e_test_user.py.\n"
        f"# gitignored — do not commit.\n"
        f"TEST_EMAIL={email}\n"
        f"TEST_PASSWORD={password}\n",
        encoding="utf-8",
    )
    os.chmod(ENV_FILE, 0o600)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="Actually write changes. Default is dry-run.")
    parser.add_argument("--reset-only", action="store_true", help="Only reset the password; don't create.")
    args = parser.parse_args()

    if not args.apply:
        print(f"[dry-run] would create or reset {TEST_EMAIL}")
        print(f"[dry-run] env file path: {ENV_FILE}")
        return

    db = init_firebase()

    uid, pw = ensure_auth_user(reset_password=True if args.reset_only else True)
    user_id = ensure_firestore_user(db, uid)

    if pw is None:
        print(f"User {TEST_EMAIL} exists and no password change requested.")
        return

    write_env_file(TEST_EMAIL, pw)
    print(f"✓ test user ready: {TEST_EMAIL}")
    print(f"  firebase uid : {uid}")
    print(f"  firestore id : {user_id}")
    print(f"  env file     : {ENV_FILE} (0600)")
    print()
    print("Run the E2E suite with:")
    print(f"  cd {ENV_FILE.parent} && env $(cat .env.e2e | xargs) npm run test:e2e")


if __name__ == "__main__":
    main()
