/Users/victoriaenso/Documents/GitHub/retailmanagement/docs/jewel_nec_pos#!/usr/bin/env python3
"""Show master product list grouped by director-level inventory category.

Reads the inventory_category, sale_ready, stocking_status, and stocking_location
fields generated by build_master_product_list.py --use-gemini.
"""
import json
from collections import Counter
from pathlib import Path

data = json.load(open(Path(__file__).resolve().parents[2] / "data" / "master_product_list.json"))
products = data["products"]

LABELS = {
    "finished_for_sale": "(1) FINISHED ITEMS — sell via NEC POS",
    "catalog_to_stock":  "(2) CATALOG ITEMS — available to purchase / stock",
    "material":          "(3) MATERIALS — to manufacture finished items",
    "store_operations":  "(5) STORE OPERATIONS — services, packaging, stationery",
}

# Group by inventory_category (written by the pipeline)
cat_map: dict[str, list] = {}
for p in products:
    cat = p.get("inventory_category", "unknown")
    cat_map.setdefault(cat, []).append(p)

# Sort order
CAT_ORDER = ["finished_for_sale", "catalog_to_stock", "material", "store_operations"]
ordered_keys = [k for k in CAT_ORDER if k in cat_map]
ordered_keys += sorted(k for k in cat_map if k not in CAT_ORDER)

W = 140
for cat_key in ordered_keys:
    items = cat_map[cat_key]
    label = LABELS.get(cat_key, cat_key)
    sale_count = sum(1 for p in items if p.get("sale_ready"))
    print(f"\n{'=' * W}")
    print(f"  {label}  — {len(items)} items  ({sale_count} sale-ready)")
    print(f"{'=' * W}")
    hdr = (f"  {'#':>4s}  {'Type':22s}  {'Material':18s}  {'Description':40s}  "
           f"{'Code':8s}  {'Qty':>4s}  {'Cost':>7s}  {'Sale':4s}  {'Stock Status':14s}  {'Location':20s}")
    print(hdr)
    print(f"  {'-' * (W - 4)}")
    for i, p in enumerate(items, 1):
        desc = (p.get("description") or "")[:40]
        mat = (p.get("material") or "")[:18]
        ptype = (p.get("product_type") or "")[:22]
        code = (p.get("internal_code") or "")[:8]
        qty = str(p["qty_on_hand"]) if p.get("qty_on_hand") is not None else ""
        price = f"${p['cost_price']:.0f}" if p.get("cost_price") else ""
        sale = "YES" if p.get("sale_ready") else "no"
        ss = (p.get("stocking_status") or "")[:14]
        loc = (p.get("stocking_location") or "")[:20]
        print(f"  {i:4d}  {ptype:22s}  {mat:18s}  {desc:40s}  "
              f"{code:8s}  {qty:>4s}  {price:>7s}  {sale:4s}  {ss:14s}  {loc:20s}")

# ── Summary ──
print(f"\n{'=' * W}")
print(f"  DIRECTOR-LEVEL SUMMARY")
print(f"{'=' * W}")
total = 0
for cat_key in ordered_keys:
    items = cat_map[cat_key]
    label = LABELS.get(cat_key, cat_key)
    w_qty = sum(1 for p in items if p.get("qty_on_hand") is not None)
    w_code = sum(1 for p in items if p.get("internal_code"))
    w_price = sum(1 for p in items if p.get("cost_price"))
    w_ready = sum(1 for p in items if p.get("sale_ready"))
    total += len(items)
    print(f"  {label:55s}  {len(items):4d} items  "
          f"({w_ready} sale-ready, {w_code} coded, {w_qty} w/qty, {w_price} w/price)")
print(f"  {'TOTAL':55s}  {total:4d} items")

# ── Stocking Status ──
print(f"\n  STOCKING STATUS:")
for s, n in Counter(p.get("stocking_status", "") for p in products).most_common():
    print(f"    {s or 'unknown':20s} {n:4d}")

# ── Stocking Location ──
print(f"\n  STOCKING LOCATION:")
for loc, n in Counter(p.get("stocking_location") or "unassigned" for p in products).most_common():
    print(f"    {loc:20s} {n:4d}")

# ── Type Breakdown ──
print(f"\n  PRODUCT TYPE BREAKDOWN:")
for cat_key in ordered_keys:
    items = cat_map[cat_key]
    label = LABELS.get(cat_key, cat_key)
    types = Counter(p["product_type"] for p in items)
    print(f"\n  {label}:")
    for t, n in types.most_common():
        print(f"    {t:25s} {n:4d}")
