"""AI / heuristic confidence scores attached to copilot recommendations.

These are baked-in confidences for *deterministic heuristic* recommendations
generated by :mod:`app.services.manager_copilot` — they don't come from a
model. The numbers are calibrated so a manager can sort by confidence and
roughly trust the ordering. We deliberately keep them under 0.9 so a true
AI-derived recommendation (with explainer) can outrank them.
"""

#: A reorder recommendation when the SKU has had recent sales — we have a
#: signal it actually moves, so we're more confident the reorder is needed.
CONFIDENCE_REORDER_HOT: float = 0.84

#: A reorder recommendation for a SKU with no recent sales. The low-stock
#: signal still matters (e.g. for safety stock), but there's no demand
#: corroboration, so confidence drops.
CONFIDENCE_REORDER_COLD: float = 0.62

#: A "stock anomaly" recommendation surfaced when Multica or the local
#: anomaly detector flags a SKU. Mid-confidence: investigate, don't auto-act.
CONFIDENCE_STOCK_ANOMALY: float = 0.71

#: A markdown-review price recommendation for slow-moving stock. The trigger
#: combines surplus inventory + lack of recent movement; we suggest, never
#: apply.
CONFIDENCE_PRICE_MARKDOWN: float = 0.67

#: A premium-price recommendation for fast-moving low-stock items with a
#: viable margin floor. Lowest-confidence recommendation in this set since
#: pricing changes have direct customer impact.
CONFIDENCE_PRICE_PREMIUM: float = 0.61
